sh_binary(
    name = "build_pip_pkg",
    srcs = ["build_pip_pkg.sh"],
    data = [
        "setup.py",
        "LICENSE",
        "README.md",
        "//tf_ops/mecab_tf:mecab_py",
        "//:libmecab",
    ],
)
