sh_binary(
    name = "build_pip_pkg",
    srcs = ["build_pip_pkg.sh"],
    data = [
        "setup.py",
        "LICENSE",
        "README.md",
        "//python/mecab:mecab",
        "//python/mecab:bind.so",
    ],
)
