name: Build and test binding modules

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      BAZEL_VERSION: 4.0.0
      TENSORFLOW_VERSION: 2.4.1
      MACOSX_DEPLOYMENT_TARGET: "10_11"

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]
        include:
          - os: macos-latest
            bazel-target: darwin
          - os: ubuntu-latest
            bazel-target: linux

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up bazel
      run: |
        curl -LO https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-${{ matrix.bazel-target }}-x86_64.sh
        chmod +x bazel-${BAZEL_VERSION}-installer-${{ matrix.bazel-target }}-x86_64.sh
        ./bazel-${BAZEL_VERSION}-installer-${{ matrix.bazel-target }}-x86_64.sh --user
        export PATH="$PATH:$HOME/bin"
        rm bazel-${BAZEL_VERSION}-installer-${{ matrix.bazel-target }}-x86_64.sh
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tensorflow-cpu==${TENSORFLOW_VERSION}
    - name: Set up workspace
      run: PIP_MANYLINUX2010=1 ./tf_configure.sh

    - name: Build and test python binding
      run: |
        bazel build -s //python/mecab:test_mecab --verbose_failures
        ./bazel-bin/python/mecab/test_mecab
    - name: Build and test tensorflow binding
      run: |
        bazel build -s //tf_ops/mecab_tf:mecab_ops_py_test --verbose_failures
        ./bazel-bin/tf_ops/mecab_tf/mecab_ops_py_test

    - name: Build python binding pip pkg and test
      run: |
        bazel clean
        bazel build -s //python:build_pip_pkg --verbose_failures
        ./bazel-bin/python/build_pip_pkg artifacts
        pip install artifacts/mecab_bind-*
        python -c 'import mecab'

    - name: Build tensorflow binding pip pkg and test
      run: |
        bazel clean
        bazel build -s //tf_ops:build_pip_pkg --verbose_failures
        ./bazel-bin/tf_ops/build_pip_pkg artifacts
        pip install artifacts/mecab_tf-*
        python -c 'import mecab_tf'
